# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpt3gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *

from input import Input
from save import Window


class UiMainWindow(object):

    def update_input(self, text_edit: QTextEdit):
        text = text_edit.toPlainText()
        self.set_input[text_edit](text)
        self.label_dict[text_edit].setText(f'({len(text.split())} cuvinte)')

    def clear(self):
        self.textEdit.setText('')
        self.textEdit_2.setText('')
        self.ck_qss.setChecked(False)
        self.ck_pyqt.setChecked(False)
        self.btn_save.setEnabled(False)
        self.btn_clear.setEnabled(False)

    def save(self):
        self.save_dialog = Window()
        self.save_dialog.show()

    def load(self):
        return

    def setupUi(self, main_window):
        self.input_ = Input()
        main_window.resize(750, 400)
        self.centralwidget = QWidget(main_window)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 431, 331))
        self.tab = QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 427, 290))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_2 = QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 427, 290))
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(460, 180, 261, 141))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_create = QPushButton(self.verticalLayoutWidget)
        self.verticalLayout.addWidget(self.btn_create)
        self.btn_load = QPushButton(self.verticalLayoutWidget)
        self.btn_load.setVisible(False)
        self.verticalLayout.addWidget(self.btn_load)
        self.btn_save = QPushButton(self.verticalLayoutWidget)
        self.btn_save.setEnabled(False)
        self.verticalLayout.addWidget(self.btn_save)
        self.btn_clear = QPushButton(self.verticalLayoutWidget)
        self.btn_clear.setEnabled(False)
        self.verticalLayout.addWidget(self.btn_clear)
        self.formLayoutWidget = QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(510, 70, 160, 51))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.ck_pyqt = QCheckBox(self.formLayoutWidget)
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.ck_pyqt)
        self.lb_qss = QLabel(self.formLayoutWidget)
        self.lb_qss.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_qss.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.lb_qss)
        self.lb_pyqt = QLabel(self.formLayoutWidget)
        self.lb_pyqt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_pyqt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.lb_pyqt)
        self.ck_qss = QCheckBox(self.formLayoutWidget)
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.ck_qss)
        main_window.setCentralWidget(self.centralwidget)

        self.set_input = {self.textEdit: self.input_.set_pyqt, self.textEdit_2: self.input_.set_qss}
        self.label_dict = {self.textEdit: self.lb_pyqt, self.textEdit_2: self.lb_qss}

        self.textEdit.textChanged.connect(lambda: self.update_input(self.textEdit))
        self.textEdit_2.textChanged.connect(lambda: self.update_input(self.textEdit_2))

        self.btn_clear.clicked.connect(lambda: self.clear())
        self.btn_save.clicked.connect(lambda: self.save())
        self.btn_load.clicked.connect(lambda: self.load())

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "PyQt5 GPT-3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("main_window", "PyQt5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("main_window", "QSS"))
        self.btn_create.setText(_translate("main_window", "Generează interfață"))
        self.btn_load.setText(_translate("main_window", "Deschide lista de interfețe salvate"))
        self.btn_save.setText(_translate("main_window", "Salvează interfața"))
        self.btn_clear.setText(_translate("main_window", "Reset"))
        self.ck_pyqt.setText(_translate("main_window", "PyQt5"))
        self.lb_qss.setText(_translate("main_window", "(0 cuvinte)"))
        self.lb_pyqt.setText(_translate("main_window", "(0 cuvinte)"))
        self.ck_qss.setText(_translate("main_window", "QSS"))


